### ISSUE TITLE
Late-CH02 11.3.5 p5 Extra semicolon in 'of the form' phrase

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#376]
remove semicolon on:
<pre>
   X& X::operator=(X&&);
</pre>

**Comment by jensmaurer** [comment]
This is odd. This pretends to be a full declaration, so a semicolon at the end seems reasonable.

**Comment by villevoutilainen** [comment]
But see paragraph 2. The things there that also pretend to be full declarations don't have semicolons.

**Comment by zygoloid** [comment]
Accepted as editorial.

Editorial decision: we should be consistent. The other six "will have the form" cases omit the semicolon. Remove it here too.
