### ISSUE TITLE
CS001 clause 2 change boilerplate text for normative references

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#377]
Use

The following documents are referred to in the text
in such a way that some or all of their content
constitutes requirements of this document. For
dated references, only the edition cited applies. For
undated references, the latest edition of the
referenced document (including any amendments)
applies.

**Comment by johelegp** [comment]
There's no difference to the current wording.

**Comment by jensmaurer** [comment]
Yes, it seems this is the same text that we already have.

**Comment by tkoeppe** [comment]
Final disposition: Rejected, we are already using the requested wording.
