### ISSUE TITLE
CS002 [intro.refs] Weed out unused normative references

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#378]
ISO/IEC, Directives, Part 2, 15.5.2:
"Only documents referred to in the text shall be
listed in Clause 2."
ISO/IEC, Directives, Part 2, 15.5.3:
"Only references cited in the text in such a way
that some or all of their content constitutes
requirements of the document shall be listed in
the Normative references clause."

The normative references list is not just a list of
important documents. It lists the references that are
part of the requirements of the document.
Please remove the concerned reference(s) to the
Bibliography or cite them explicitly as a requirement
(shall) in the text, as indicated in the DIS edited
text.

Specifically:

- ISO/IEC 2382 (only part 1 is cited in clause 3)
- ISO 8601 is only cited (undated) in Table 99 but not normatively (i.e. not as a requirement "shall"). Please move it to the bibliography.
- ISO/IEC 10646-1:1993: This document doesn't exist or was withdrawn. Please correct.
- ISO/IEC/IEEE 60559:2011: This document is not cited normatively (i.e. shall). Please move to the Bibliography.
- UAX #29 This document is not cited normatively (i.e. shall). Please move to the Bibliography.

**Comment by jensmaurer** [comment]
My guess is that ISO/CS was text-searching for the normative references and looking for a "shall" in the immediate vicinity. Given that we usually don't do "shall" for requirements on implementations, that check probably failed.

**Comment by jensmaurer** [comment]
@zygoloid , The edited DIS document provided for CS016 #392 has highlighting for the specific normative references they feel are not properly referenced.

**Comment by jensmaurer** [comment]
Analysis of "normative references" marked in the edited DIS:
- ISO 8601:2004: used for %z format specifier (offset from UTC) in [time.format]
Suggested action: Add in [time.format] p2: "... as described in Table 99; the formats specified in ISO 8601:2004 shall be used where so described."
- ISO/IEC/IEEE 60559:2011: used in numeric_limits and totalOrder as an implementation option; not "shall"-ified
Suggested action: Since it's not a normative requirement to implement IEC 60559, we should this to the bibliography.
- UAX#29: used in format.string.std in a "should" phrasing, not shall.
Suggested action: Since it's not a normative requirement, we should move this to the bibliography.

**Comment by tkoeppe** [comment]
Final disposition: Accepted with modifications: References to ISO/IEC/IEEE 60559:2011 and UAX#29 have been moved to the Bibliography; the mention of "parts" of ISO 2382 has been removed, and the normative relevance of ISO 8601:2004 has been called out.
