### ISSUE TITLE
JP003 3.30 Fix cross-reference to [expr.const]

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#379]
It may be difficult to understand what the section
reference (7.7) means in the following description. 

Evaluation of a constant expression
never exhibits behavior explicitly
specified as undefined in Clause 4
through Clause 15 of this document
(7.7).

Move cross-reference to expr.const as follows:

Evaluation of a constant expression (7.7)
never exhibits behavior explicitly
specified as undefined in Clause 4
through Clause 15 of this document.

JP5

**Comment by tkoeppe** [comment]
Final disposition: Accepted.
