### ISSUE TITLE
JP004 17.11.2.2 p5 Bad ordering returned

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#380]
If v is unordered value, the following expression
returns v, but it should return
partial_ordering::unordered.
Returns: v < 0 ? partial_ordering::greater : v > 0 ?
partial_ordering::less : v.

Change expression as follows:
Returns v.is_ordered ? (v < 0 ?
partial_ordering::greater : v > 0 ?
partial_ordering::less : v) :
partial_ordering::unordered

JP6

**Comment by jensmaurer** [comment]
I think the consensus on the -lib reflector was NAD.

**Comment by zygoloid** [comment]
No consensus for change. If `v` is unordered, then returning `v` and returning `partial_ordering::unordered` are identical, so the suggested change is equivalent to the existing text.

**Comment by tkoeppe** [comment]
Final disposition: Rejected; see above for details.
