### ISSUE TITLE
JP006 20.7.4 p3 struct vs. class for variant_alternative

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#382]
Since the variant_alternative is a struct type, “class" in the following definition should be changed to “struct”.
template&lt;size_t I, class T> class variant_alternative&lt;I, const T>;

Change “class” to “struct” as follows:
template&lt;size_t I, class T> struct variant_alternative&lt;I, const T>;

**Comment by tkoeppe** [comment]
Final disposition: Accepted.
