### ISSUE TITLE
JP007 20.11.3.9 p4 spell well-formed with a hyphen

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#383]
In the following sentence, “well formed” should be “well-formed”.
The expression dynamic_cast&lt;typename shared_ptr&lt;T>::element_type*>(r.get()) is well formed.

JP9

**Comment by johelegp** [comment]
The resolution for this one is the same as the previous issue.

**Comment by tkoeppe** [comment]
Final disposition: Accepted.
