### ISSUE TITLE
JP009 20.12.3.2 p11 Bad syntax for variadic template declaration

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#385]
In the following definition, first argument of the new_object function should have “…” after class.
template&lt;class T, class CtorArgs...> [[nodiscard]] T* new_object(CtorArgs&&... ctor_args);

Change the example as follows:
template&lt;class T, class... CtorArgs> [[nodiscard]] T* new_object(CtorArgs&&... ctor_args)

JP11

**Comment by tkoeppe** [comment]
Final disposition: Accepted.
