### ISSUE TITLE
JP010 31.8.1 p25 memcpy needs a pointer as its first argument

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#386]
In the following example, the first parameter of memcpy should be pointer value:
memcpy(expected, this, sizeof(*this));

Change the example as follows
memcpy(&expected, this, sizeof(*this));

JP12

**Comment by jensmaurer** [comment]
This was fixed by commit e674373e2515868ca17b24157f30515fad62b8e6 in the main branch and needs to be cherry-picked to the c++20 branch.

**Comment by tkoeppe** [comment]
Final disposition: Accepted.
