### ISSUE TITLE
JP011 Bad PDF bookmarks

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#387]
Regarding the PDF file of the specification, when the item of bookmarks is clicked, the displayed page is different from clicked item.

Rebuild the bookmarks.

JP1

**Comment by jensmaurer** [comment]
This is probably due to ISO/CS messing with the document.

**Comment by zygoloid** [comment]
It looks like the bookmarks are all off by one page. ISO/CS replaced our one front cover sheet with two pages. Perhaps adding a blank page after our (replaced) cover sheet will help.

**Comment by jensmaurer** [comment]
I think they did that to the published C++17 standard as well, leading to a broken PDF in their web store. Maybe we should simple communicate with them about the problem and ask them how they want it fixed for good? We can certainly produce a blank page "replace me, too", but they should know about it.

**Comment by jensmaurer** [comment]
Editorial meeting: Recreate the ISO cover pages in LaTeX to hopefully avoid ISO/CS from attaching the cover pages themselves. Also change the header to state the document number.
