### ISSUE TITLE
CS012 Use correct text for foreword

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#388]
Please use the Foreword provided:

ISO (the International Organization for Standardization) and IEC (the International Electrotechnical Commission) form the specialized system for worldwide standardization. National bodies that are members of ISO or IEC participate in the development of International Standards through technical committees established by the respective organization to deal with particular fields of technical activity. ISO and IEC technical committees collaborate in fields of mutual interest. Other international organizations, governmental and non-governmental, in liaison with ISO and IEC, also take part in the work.
The procedures used to develop this document and those intended for its further maintenance are described in the ISO/IEC Directives, Part 1. In particular, the different approval criteria needed for the different types of document should be noted. This document was drafted in accordance with the editorial rules of the ISO/IEC Directives, Part 2 (see www.iso.org/directives).
Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. ISO and IEC shall not be held responsible for identifying any or all such patent rights. Details of any patent rights identified during the development of the document will be in the Introduction and/or on the ISO list of patent declarations received (see www.iso.org/patents) or the IEC list of patent declarations received (see http://patents.iec.ch). 
Any trade name used in this document is information given for the convenience of users and does not constitute an endorsement.
For an explanation of the voluntary nature of standards, the meaning of ISO specific terms and expressions related to conformity assessment, as well as information about ISO's adherence to the World Trade Organization (WTO) principles in the Technical Barriers to Trade (TBT), see www.iso.org/iso/foreword.html. 
This document was prepared by Joint Technical Committee ISO/IEC JTC 1, Information technology, Subcommittee SC 22, Programming languages, their environments and system software interfaces.
This sixth edition cancels and replaces the fifth edition (ISO/IEC 14882:2017), which has been technically revised.
The main changes compared to the previous edition are as follows:
—	xxx xxxxxxx xxx xxxx
Any feedback or questions on this document should be directed to the user’s national standards body. A complete listing of these bodies can be found at www.iso.org/members.html.

**Comment by jensmaurer** [comment]
Differences to our existing text:

- "different types of document" (note no "s" after "documents")
- "see the following URL: www.iso.org/iso/foreword.html" -> ", see (url)"
- "It also incorporates the Technical Specifications" -> drop in this position; maybe add to the "main changes" list

**Comment by zygoloid** [comment]
> * "different types of document" (note no "s" after "documents")

Looks like ISO/CS fixed this since they gave us the text for the DIS :)

> * "see the following URL: [www.iso.org/iso/foreword.html](http://www.iso.org/iso/foreword.html)" -> ", see (url)"

This was an intentional change to fix an overfull hbox. I'll add a manual linebreak instead.

> * "It also incorporates the Technical Specifications" -> drop in this position; maybe add to the "main changes" list

This is the part they seemed upset by, based on their edited document. I'll integrate this into the main changes.

**Comment by tkoeppe** [comment]
Final disposition: Accepted.
