### ISSUE TITLE
JP013 Harmonize parentheses after function names

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#389]
In some cases, function references in a sentence has no parentheses attached and others has attached parentheses.

For example, std::terminate has no parentheses attached in 14.6.1.  But, std::uncaught_exceptions has attached parentheses in 14.6.2.

Remove the parentheses.

JP4

**Comment by tkoeppe** [comment]
Final disposition: Accepted with modifications, see above.
