### ISSUE TITLE
JP014 PDF links point to text, not to title of annex

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#390]
Regarding the PDF file of the specification, when the link of annex X is clicked, the displayed position is different from the former document.
(When the link of annex X is clicked:
    C++17 standard
      jump to the chapter title of annex X.
    This document
      jump to the beginning of text of annex X.)
This behaviour may cause the confusion.

Reset the link.

JP3

**Comment by jensmaurer** [comment]
This is reproducible with a current PDF build of the draft.

**Comment by tkoeppe** [comment]
Final disposition: Accepted.
