### ISSUE TITLE
JP015 PDF links to clauses point to first subclause instead

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#391]
Regarding the PDF file of the specification, when the link of the clause X is clicked, X.1 is displayed.

Reset the link.

JP2

**Comment by jensmaurer** [comment]
This is reproducible with a current PDF build of the draft.

**Comment by johelegp** [comment]
Started with https://github.com/cplusplus/draft/commit/beb88157cc49f76677fc467db8ec4a523dbc41d0.

**Comment by jensmaurer** [comment]
Curiously enough, this only occurs with references to entire clauses, not with references to subclauses that don't have hanging paragraphs.
Example: A reference to 6.4 [basic.scope] correctly hyperlinks to [basic.scope], not to its first subclause [basic.scope.declarative].

**Comment by jensmaurer** [comment]
Experimentally replacing our home-grown \clauselabel with the standard \label in the definition of \Sec in macros.tex restores the correct behavior, but of course kills the "Clause 7" label names.

**Comment by tkoeppe** [comment]
Final disposition: Accepted.
