### ISSUE TITLE
CS016 Address 39 specific comments in edited DIS document

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#392]
An edited file of the DIS has been prepared by ISO/CS. 
Please note that the DIS edited file contains 39 comments on specific elements of the document, which need to be fixed so the document complies with the Directives, Part 2.

Please take all the comments in to consideration to avoid rejection at the next stage.

**Comment by jensmaurer** [comment]
@zygoloid , do you have the "edited file of the DIS" this comment is talking about? Please send it to the co-editors.

**Comment by zygoloid** [comment]
I don't have it; I have requested that ISO/CS provide us with this file.

**Comment by zygoloid** [comment]
I've made a pass through these, and I think #393 captures the only remaining open issue here.

**Comment by tkoeppe** [comment]
- page headers: will be fixed as part of the publication cover sheet
- Say "Annex X", not just "X": implemented by cplusplus/draft@1ae624813d7a26c1757156c23487745e89be64f2

**Comment by tkoeppe** [comment]
Final disposition: Accepted with modifications: All but one comment from the annotated document have been accepted and addressed. The one rejected comment is a reference to CS-19, see there for the rejection rationale.
