### ISSUE TITLE
CS018 Excise hanging paragraphs and solitary subclauses

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#394]
Hanging paragraphs are not allowed in ISO publications (i.e. all paragraphs must belong to the smallest sublevel).
Also, a sublevel is only allowed if there are at least 2 items at the same sublevel (i.e. no x.1 if there is no x.2).

Please refer to the few occurrences indicated in the DIS text and correct as necessary throughout the document.

**Comment by tkoeppe** [comment]
Tentatnive disposition: Acccepted. @zygoloid, @jensmaurer are we going to fx/have we fixed _all_ hanging paragraphs now? Should we leave this open until the page-by-page review? I'll add an entry to cplusplus/draft#4219  regardless.

**Comment by jensmaurer** [comment]
Yes, hanging paragraphs have been machine-identified and machine.fixed. This is Accepted.

**Comment by tkoeppe** [comment]
Thanks, Jens!

Final disposition: Accepted.
