### ISSUE TITLE
CS019 Consider removing cross-references and indexes to reduce page count

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#395]
Considering the end user is charged by the page count, are the 200 pages of cross-references and indexes necessary? 
Should they be moved to an electronic attachment instead?

**Comment by jensmaurer** [comment]
Some NBs seem to cap the price of a standard, independent of the number of pages. For example, ISO 9899 (the C standard) is less than half the number of pages of ISO 14882:2017. Yet:
- DIN charges 229.20 EUR for C++ and 210.40 EUR for C.
- ANSI charges 232 USD for either.
(PDF download in all cases)

**Comment by zygoloid** [comment]
ANSI sells the INCITS version of C++17 for $116: https://webstore.ansi.org/Standards/INCITS/INCITSISOIEC1488220172018
ANSI also sells the INCITS version of C18 for $116: https://webstore.ansi.org/Standards/INCITS/INCITSISOIEC989920182019

So it looks like rejecting this comment would be reasonable.

Suggested response:

**Rejected.** The primary purpose of these cross-references and indexes is to provide hyperlinking to positions within the standard text. We do not believe that purpose can be addressed by an electronic attachment that is provided separately from the standard. The previous two revisions of ISO/IEC 14882 (:2014 and :2017) were only published digitally, and we expect that to also be the case for this revision. Multiple digital publishers (for example, ANSI and INCITS) appear to put an upper bound on the amount they charge, independent of the number of pages, and given the size of our standard without these appendixes, their addition would not increase the cost through those publishers.

**Comment by tkoeppe** [comment]
Final disposition: Rejected, see above for detailed response.
