### ISSUE TITLE
CS016-2 [intro.defs] terms and definitions cannot cross-reference into the main text body

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#397]
In the terminological entries, the cross-references are used to point to other terms defined in Clause 3, not to the subclause where the term is used.Please correct throughout.

**Comment by jensmaurer** [comment]
Agreed: Go with blind removal of cross-references.

**Comment by jensmaurer** [comment]
@zygoloid , do you want to askISO/CS whether cross-references to the main body text in "note X to entry" is acceptable, which would allow us to salvage some of the cross-reference, or should I go with blind removal?

**Comment by zygoloid** [comment]
Let's assume we're allowed to cross-reference into the body text in the notes. Cross-references from notes that say how the definition is used seem too useful to remove unless we really need to.

**Comment by tkoeppe** [comment]
The rationale is a bit strange: our cross references aren't to where the term is used, but where parts of the term's _definition_ are defined.

**Comment by tkoeppe** [comment]
See #392 for final disposition of the single ballot comment that contains this detail.
