### ISSUE TITLE
CS016-3 Notes/examples to be numbered and in separate paragraphs

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#398]
This is not ISO practice. Please remove.

Note and examples are to appear in a separate paragraph, in font size 10 (or rather, one point smaller than regular text in this case).
Please change throughout.

See comment above about Notes.
When several notes appear in the same subclause, they are to be numbered NOTE 1, NOTE 2, etc.
Please correct throughout.

**Comment by tkoeppe** [comment]
See #392 for final disposition of the single ballot comment that contains this detail.
