### ISSUE TITLE
CS016-5 [intro.defs] ISO 2382-1:1993 is withdrawn

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#400]
ISO/IEC 2382-1 is withdrawn. Please cite either ISO/IEC 2382:2015, ISO/IEC 2382-36:2019 or ISO/IEC 2382-37:2017.

**Comment by zygoloid** [comment]
Ugh, OK. We'll need to figure out which terms we're actually using from ISO/IEC 2382 and which part they live in.

**Comment by jensmaurer** [comment]
At least it's publicly available:

https://standards.iso.org/ittf/PubliclyAvailableStandards/index.html

**Comment by jensmaurer** [comment]
Approach: Change ISO 2382 to an undated reference; no other changes.

**Comment by jensmaurer** [comment]
Accepted.

**Comment by tkoeppe** [comment]
See #392 for final disposition of the single ballot comment that contains this detail.
