### ISSUE TITLE
CS016-6 [intro.refs] ISO/IEC 10646-1:1993 is withdrawn

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#401]
This document doesn't exist or was withdrawn. Please correct.

Note: used in [depr.locale.stdcvt.req] for the definition of UCS-2

**Comment by jensmaurer** [comment]
-lib discussion: http://lists.isocpp.org/lib/2020/09/17410.php

**Comment by zygoloid** [comment]
I think we should reject this comment. I don't see any rule in https://www.iso.org/sites/directives/current/part2/index.xhtml#_idTextAnchor118 that disallows referencing a withdrawn document, and there is no current document that we can cite that defines the term in question.

**Comment by zygoloid** [comment]
For rationale, something like "We are aware of the issue and the committee is working to remove the functionality from our standard that depends on functionality removed in ISO/IEC 10646:2011, but until that work is complete, there is no other source for the definition of UCS-2 that is normatively referenced by ISO/IEC 14882."

But while we're here, we should update the reference from ISO/IEC 10646-1:1993 to ISO/IEC 10646:2003, which seems to be the most recent revision of ISO/IEC 10646 that defined UCS-2.

**Comment by zygoloid** [comment]
@jensmaurer Can you double-check my assertion that :2003 is the right thing to be referencing here?

**Comment by jensmaurer** [comment]
https://www.iso.org/standard/39921.html says
"ISO/IEC 10646:2003 ... specifies a two-octet (16-bit) BMP form of the UCS: UCS-2;"

whereas https://www.iso.org/standard/56921.html
ISO/IEC 10646:2012
doesn't mention UCS-2 anymore.

**Comment by zygoloid** [comment]
Accepted with modification.

**Comment by tkoeppe** [comment]
See #392 for final disposition of the single ballot comment that contains this detail.
