### ISSUE TITLE
DE-079 17.3.3 [limits.syn], 17.3.5 [numeric.limits] has_denorm

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#506]
The has_denorm and has_denorm_style traits in numeric_limits are actively misleading users and should therefore be deprecated as soon as possible. Their corresponding macros have been declared as “an obsolescent feature” in the latest ISO/IEC 9899 WD.

Proposed change:

Apply P2614R1.

**Comment by brycelelbach** [comment]
The proposed resolution is to adopt P2614 https://github.com/cplusplus/papers/issues/1278

P2614 is undergoing Library Evolution electronic polling, although that will have to be redone due to the poll stating the wrong ship vehicle (C++26 instead of C++23). Still, this doesn't need more Library Evolution input.

**Comment by mattkretz** [comment]
> P2614 is undergoing Library Evolution electronic polling, although that will have to be redone due to the poll stating the wrong ship vehicle (C++26 instead of C++23).

Can't we just do a quick poll in LEWG in Kona instead? I.e. it seems like there should be an "evolution" poll on whether we want to do it for 23. I could also schedule it for SG6 on Monday, so LEWG could have the SG6 direction as input.

**Comment by brycelelbach** [comment]
No. The Library Evolution poll is nearly done. We will have the results
during the meeting. Any pills we take at Kona will have to be confirmed by
electronic poll anyways

--
Bryce Adelstein Lelbach aka wash (he/him/his)
US Programming Language Standards Chair
ISO C++ Library Evolution Chair
Principal Architect @ NVIDIA
--

**Comment by JeffGarland** [comment]
@brycelelbach exactly what day will we have them? I'd like to schedule this Mon/Tue in Kona - maybe I'll just do it 'at risk'.

**Comment by brycelelbach** [comment]
Probably tomorrow.

**Comment by mattkretz** [comment]
As the author of P2614, note that I will be chairing SG6 on Monday afternoon.

**Comment by JeffGarland** [comment]
Let's plan to see this in LWG on Tuesday morning.

**Comment by JeffGarland** [comment]
@mattkretz Scheduled for 8 am in LWG this morning

**Comment by JeffGarland** [comment]
LWG reviewd in Kona and requested changes -- will see again after updates.

**Comment by JeffGarland** [comment]
LWG has reviewed the updated paper and will move for C++23 in Kona

**Comment by JeffGarland** [comment]
@brycelelbach We still need final poll results from LEWG

**Comment by JeffGarland** [comment]
https://wiki.edg.com/bin/view/Wg21kona2022/LWG20221108-EM

poll: put P2614r2 into C++23?

F | A | N
-- | -- | --
6 | 0 | 0

**Comment by jwakely** [comment]
Accepted with modification.
