### ISSUE TITLE
FR-006-022 19.6.4.6 [stacktrace.basic.nonmem] Avoid needless templatization

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#507]
```
operator<<(basic_ostream<charT, traits>& os, const basic_stacktrace<Allocator>& st);
```
does not need to be templatized on char or traits.
It could also be specified as a hidden friend to help compile times and diagnostics

**Comment by jwakely** [comment]
This is [LWG 3515](https://wg21.link/lwg3515) which was sent to LEWG and I think was in their most recent electronic polls.

https://github.com/cplusplus/papers/issues/1298

**Comment by brycelelbach** [comment]
Indeed it was. We should have the result of that poll in a day or so, and don't have any further action here. All yours.

**Comment by JeffGarland** [comment]
Tentatively scheduled from LWG on Monday in Kona

**Comment by JeffGarland** [comment]
LWG approved for c++23 in Kona

https://wiki.edg.com/bin/view/Wg21kona2022/LWG20221107-EA

poll: move LWG3515 to ready? 

F | A | N
-- | -- | --
9 | 0 | 2

**Comment by jensmaurer** [comment]
Accepted.
