### ISSUE TITLE
IT-096 22.10.17.4 Add function_ref

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#512]
move_only_function` (P0288) and `function_ref` (P0792) should be delivered together as part of C+ `+23.
`function_ref` (P0792) has been a driving force in the design and standardization of `move_only_function` (P0288), and we believe it did not make the cut for C++23 for timing and organizational reasons. Providing only `move_only_function` (P0288) is inadequate for the users of C++23.

We request to consider the inclusion of function_ref` (P0792) as part of the final draft.

**Comment by brycelelbach** [comment]
The proposed resolution is to adopt P0792 https://github.com/cplusplus/papers/issues/256.

**Comment by brycelelbach** [comment]
Rejected, no consensus for change. See P0792 https://github.com/cplusplus/papers/issues/256 for more details.
