### ISSUE TITLE
FR-001-019 31.7.10 [print.fun] Synchronizing with a terminal

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#537]
Please consider adopting P2531
"Should the output of std::print to a terminal be synchronized with the underlying stream?" as it may be a behaviour change to adopt it late

**Comment by brycelelbach** [comment]
[P2531](https://wg21.link/P2531) is the list of issues to be moved at the 2022-02 virtual plenary. I presume the French meant [P2539](https://wg21.link/P2539), which is undergoing electronic polling in Library Evolution right now.

**Comment by brycelelbach** [comment]
Marking this one as a duplicate of #536

**Comment by jensmaurer** [comment]
Accepted with modification.
