### ISSUE TITLE
**-002 Additional information in Clause 2

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#544]
Clause 2 cannot include additional paragraphs. Please remove paragraphs 2-4.

**Comment by jensmaurer** [comment]
Those paragraphs are:

2 The library described in ISO/IEC 9899:2018, Clause 7, is hereinafter called the C standard library.
3 The operating system interface described in ISO/IEC 9945:2009 is hereinafter called POSIX.
4 The ECMAScript Language Specification described in Standard Ecma-262 is hereinafter called ECMA-262.

Other comments want us to refer to POSIX or C using the ISO numbers (9945 and 9989, respectively), so that would be consistent with that.

I note we have plenty of cross-references to the C standard library in the shape of "See also: ISO C 7.22.3", but that's a macro and easily changed to "ISO/IEC 9899:2018 subclause 7.22.3" globally, if need be.

**Comment by jensmaurer** [comment]
@jwakely , this is mostly a library problem, I think. Any opinion?

**Comment by tkoeppe** [comment]
This material _could_ possibly go into a new Introduction clause?

**Comment by jensmaurer** [comment]
Probably not. This is more about how we reference to third-party standard, and ISO doesn't want us to use well-known words for that.

**Comment by tkoeppe** [comment]
Progress: clarify with CS. We seem to be compliant with the Drafting Directives. 10.6 seems to permit referring to documents by title.

**Comment by tkoeppe** [comment]
I asked ISO about this, and they replied:

> DP2, 15.1 state what is the purpose of the content of Clause 2. It is a place to put references to which there is an explicit requirement, nothing else.  I would suggest moving this information to the first time the references are present in the document. Otherwise, another option would be to format this information as footnotes.

Indeed, the DP2 say that "Information on how these references apply is found in the place where they are cited in the document, and not in the Normative references clause.".

Maybe we can move the explanation to the first point of use, as recommended?

**Comment by jensmaurer** [comment]
Neither option seems attractive. We don't want to introduce vital terminology (in this case: abbreviated name for a foreign standard) in a footnote, nor do we want to hide such vital terminology at the first point of use (which might be insignificant, in the grand scheme of things).

I'll prepare a pull request to replace some references with their full number, and introduce the abbreviated name in the intro section where we need it often (e.g. library intro for ISO C or filesystem intro for POSIX). Let's see what remains.

**Comment by tkoeppe** [comment]
We've only got ECMAScript and POSIX to deal with here, don't we? For ECMAScript wouldn't it suffice to make that definition in the [regex] clause?

**Comment by jensmaurer** [comment]
@tkoeppe, see pull request.
