### ISSUE TITLE
**-005 [intro.refs] Incorrect title for ISO/IEC/IEEE 9945:2009

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#547]
Please update the reference in Clause 2 and in the document. Since there is no specific element referenced this reference shall be undated. The correct title is: Information technology — Portable Operating System Interface (POSIX®) Base Specifications, Issue 7

**Comment by jensmaurer** [comment]
"Since there is no specific element referenced"

We want to keep the dated reference, so we need to reference a specific element. Unless @jwakely tells us silently upgrading to the latest and greatest is fine. (This is mostly for the filesystem library, I think, so probably the latest and greatest is actually fine.)

**Comment by jensmaurer** [comment]
The ISO Directives, Part 2, mention other reasons why a dated reference might be preferable, including that it might not be desired to automatically incorporate future changes into our standard. This is our rationale, in general.

However, if we need to sidestep the issue, we could add a more precise reference in e.g. [fs.op.create.directory] (for mkdir); suggestion: "as if by mkdir as specified in ISO/IEC/IEEE 9945:2009 volume 2, chapter 3, with a second argument of `static_cast<int>(perms::all)?."

**Comment by JohelEGP** [comment]
<https://www.iso.org/ISO-house-style.html#iso-hs-s-text-r-r-ref_withdrawn>
also mentions that the reference and first cross-reference of a replaced document needs a footing like
> 1\) Cancelled and replaced by ISO 5725-2:2019.

**Comment by tkoeppe** [comment]
I am not sure why not referring to a specific element requires using an undated reference; I will push back on that.

**Comment by tkoeppe** [comment]
Reject: the justification seems wrong, in fact, the wrong way round; we do need the dated references for reasons stated in 10.4.
