### ISSUE TITLE
**-009 [intro.defs] Terms and definitions are only allowed in Clause 3.

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#551]
Please delete paragraph 3 as Clause 3 cannot include anything other than term entries and the template text (introductory paragraphs 1 and 2). The only place to define a term in the document is in Clause 3, please add the term entries as necessary instead of having them in other places in the document.

**Comment by jensmaurer** [comment]
Paragraph 3 is mostly explanatory, so deleting it is possible.

Not doing what paragraph 3 advertises (local term definitions) is a lot of work and will substantially reduce the quality of the document. (Are we now defining "core constant expression" in clause 3? This is a two-page definition or so.)

**Comment by jensmaurer** [comment]
@tkoeppe, other than deleting p3, I can't see us doing what this comment wants.

**Comment by tkoeppe** [comment]
Decision: delete the bad paragraph, leave everything else as is and explain that we have local terms that don't make sense in Clause 3.

**Comment by tkoeppe** [comment]
Fixed by 4d603c640dd47c71f84bbce55416302efab8b298.
