### ISSUE TITLE
**-010 [intro.defs] Superfluous angular bracket domains

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#552]
Domains (information in angle brackets) is used to distinguish two or more term entries with the same term.

The use of domains seems unnecessary in this document when there is only one term entry with the same term. It is suggested to remove this information when it is not necessary.

**Comment by jensmaurer** [comment]
This is just a suggestion, but we should review superfluous domains.

**Comment by tkoeppe** [comment]
I agree, the domain is valuable because regular-English sounding names have domain-specific meaning here, and the domain is important to establish context.

**Comment by tkoeppe** [comment]
Noted.
