### ISSUE TITLE
**-011 [intro.defs] Term not used in the document

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#553]
terms defined in 3.2, 3.18, 3.29, 3.66

Please use this term in the document or remove it from Clause 3.
[ISO/IEC Directives, Part 2, 16.5.4](https://www.iso.org/sites/directives/current/part2/index.xhtml#_idTextAnchor218): “Only terms which are used in the document shall be listed in the Terms and definitions clause.”

**Comment by jensmaurer** [comment]
Removing should be fine if actually unused.

**Comment by jensmaurer** [comment]
3.18 is "direct-non-list-initialization", which is used pervasively in the verb form "direct-non-list-initialized".

3.29 the term "iostream class" is used twice, but not in a way that would need a definition here. Removed.

3.66 "unspecified behavior" is used pervasively as "it is unspecified whether ..."

3.2 "arbitrary-positional stream" and 3.48 "repositional stream" are removed, because unused.

**Comment by jensmaurer** [comment]
We need a decision for

3.18 is "direct-non-list-initialization", which is used pervasively in the verb form "direct-non-list-initialized".
3.66 "unspecified behavior" is used pervasively as "it is unspecified whether ..."

**Comment by JohelEGP** [comment]
> 3.66 "unspecified behavior" is used pervasively as "it is unspecified whether ..."

The term should be "unspecified",
or the use like "it is unspecified behavior whether ...".
Remember this from the directives:
> 16.5.6	Definitions
>
> The definition shall be written in such a form that it can replace the term in its context.

**Comment by tkoeppe** [comment]
Decision: delete the three; reword "direct-non-list-initialization", keep "unspecified behaviour".

**Comment by tkoeppe** [comment]
@jensmaurer, @zygoloid ISO really wants us to remove "unspecified behavior".

Could we maybe change it to just define "unspecified", and say:

> &lt;behavior&gt; **unspecified:** correct and dependent on the implementation

**Comment by jensmaurer** [comment]
Suggestion: Let's rephrase some "unspecified" thing in the standard proper to use the phrasing "unspecified behavior".

**Comment by tkoeppe** [comment]
This is nice, thanks!
