### ISSUE TITLE
**-013 3.12 [defns.component] Expand CE acronym

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#555]
The first time an acronym is used it should be presented in parentheses next to the full term.

Add the parentheses to CE next to condition expression if this is its acronym.

NOTE: This should refer to 3.14 [defns.const.subexpr]

**Comment by jensmaurer** [comment]
This is confused. CE is a meta-variable, not an acronym.

**Comment by tkoeppe** [comment]
Noted.
