### ISSUE TITLE
**-014 [intro.defs] Do not number singular examples

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#556]
If only one example is present in a term entry in Clause 3, it shall not be numbered (different from the rule for notes to entry).

Please unnumber the examples in Clause 3 if there is only one in a term entry. Also remove the colon.

**Comment by jensmaurer** [comment]
Check the Directives, Part 2, whether that is true (why is clause 3 so different from the rest?), and fix accordingly.

Didn't we have a LaTeX patch that removed the numbering if only a single note (or example) was present? Now seems the time to apply it, at least selectively.

**Comment by jensmaurer** [comment]
ISO/IEC Directives, Part 2, 9th ed:

25.3 Numbering and subdivision
Within a given clause or subclause, examples shall be numbered sequentially. The numbering restarts
at each new subdivision. **A single example in a subdivision shall not be numbered.**

**Comment by tkoeppe** [comment]
Accepted and fixed. I don't know what "please remove the colon" is referring to, though.

**Comment by JohelEGP** [comment]
FWIW, the examples from the directives use a colon: <https://www.iso.org/sites/directives/current/part2/index.xhtml#_idTextAnchor228>.

**Comment by tkoeppe** [comment]
Yes, maybe that's what they were referring to, as in "you removed a colon (from the notes to entry)"...
