### ISSUE TITLE
**-016 3.48 [defns.repositional.stream] seeking "to" a position

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#558]
“seek to a position” is unclear, do you mean “seek a position”?

**Comment by jwakely** [comment]
The text is correct as written, the suggestion is wrong.

But this definition (and 3.2 arbitrary-positional stream) are never used anyway, so could be deleted. See #553

**Comment by jensmaurer** [comment]
Removed term via patch for #553.
