### ISSUE TITLE
**-017 [intro.refs] Italicize and add cross-references for terms

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#559]
Insert cross references for terms defined in Clause 3 which are used within other term entries Clause 3.

Please insert cross references and modify the existing cross references so the term is italicized and it is accompanied by the term entry number in parentheses (see example below).
Every arbitrary-positional stream is also a repositional stream (3.48).

**Comment by jensmaurer** [comment]
Can do.

**Comment by tkoeppe** [comment]
16.5.4: "Within a terminological entry, cross-references may also be made to other terminological entries."

**Comment by tkoeppe** [comment]
Also via HS References in Clause 3 (Terms and definitions)

**Comment by tkoeppe** [comment]
Fixed by eb7f0bcbff2af109643089ef36dfe67040a27f4a
