### ISSUE TITLE
JP2-022 7.5.5.2 p5 [expr.prim.lambda.closure] Attributes on lambdas

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#564]
“the type of the corresponding function call operator or operator template” sounds like a function type. It would be better to use “the closure type”.

In "An attribute-specifier-seq in a lambda-declarator appertains to the type of the corresponding function call operator or operator template.", replace "function call operator or operator template" with "closure type"

**Comment by jensmaurer** [comment]
The comment is wrong; we mean the function type of the synthesized function call operator (template).

**Comment by tkoeppe** [comment]
Noted.
