### ISSUE TITLE
JP7-027 20.3.4.1 p3 [out.ptr.t] Class definition after example

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#569]
There should be a class template definition before the example.

Move class template definition before p1.

**Comment by jensmaurer** [comment]
This is increasingly common style: Present an example how to use a facility before defining the facility. We do that in [ranges] quite a bit.

@jwakely to chime in.

**Comment by jwakely** [comment]
Reject

**Comment by jensmaurer** [comment]
There was no consensus for a change. Introducing a facility by showing an example use is considered reader-friendly.

**Comment by tkoeppe** [comment]
Noted.
