### ISSUE TITLE
JP8-028 20.3.4.3 p3 [inout.ptr.t] Move class definition before example

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#570]
There should be a class template definition before the example.

Move class template definition before p1.

**Comment by jensmaurer** [comment]
This is increasingly common style: Present an example how to use a facility before defining the facility. We do that in [ranges] quite a bit.

@jwakely to chime in.

**Comment by jwakely** [comment]
Reject

**Comment by tkoeppe** [comment]
Noted.
