### ISSUE TITLE
**-031 Foreword: update needed

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#573]
Please contact the editor to obtain the latest version of the Foreword (and other template texts) before submitting the document for FDIS ballot.
For example, the current foreword is missing the last line and the third paragraph has been changed.

**Comment by tkoeppe** [comment]
Bill already sent me the foreword, thanks!

**Comment by tkoeppe** [comment]
I'm not sure what "the last line and the third paragraph" is referring to, though. Maybe Clause 2 or 3?

**Comment by jensmaurer** [comment]
I guess the "last line and the third paragraph" of the Foreword section in the DIS.

**Comment by tkoeppe** [comment]
Ah yes, sorry: I did have a foreword in the actual DIS, but it's an old version I took from the LFTS PDTS. I have received updated text and will apply it.

**Comment by tkoeppe** [comment]
Accepted (and done).
