### ISSUE TITLE
**-032 Use Cambria and Courier New fonts exclusively

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#574]
The font for the document shall be Cambria, use Courier New only for code. No other font shall be used.

Please change the font to Cambria before submitting the document for FDIS ballot.

**Comment by jwakely** [comment]
We should reject this.

**Comment by tkoeppe** [comment]
I'm in the process of rejecting this for the TS, too, but they keep pushing hard. They looked up some free&open Linux package that "looks a bit like Cambria and we could use in LaTeX"...

**Comment by jensmaurer** [comment]
That doesn't address our other "italics", e.g. for grammar non-terminals and our localized term definitions. Any ideas on those? Or can we bargain a bit here: use Cambria and leave the rest alone?

**Comment by jensmaurer** [comment]
@tkoeppe, it seems the stance of the editors is rather clear here (what we have is fine). For you to discuss further with ISO/CS.

**Comment by tkoeppe** [comment]
I'll discuss this at least once; leave this with me for now.

**Comment by tkoeppe** [comment]
**Cambria and Courier New:**

![image](https://github.com/cplusplus/nbballot/assets/6378233/24f8b507-bb82-4d5a-85a7-213d9a3944c4)


<br>

**Roboto Serif and Roboto Mono:**

![image](https://github.com/cplusplus/nbballot/assets/6378233/ef58e272-b1f9-4e47-a023-805da82377a4)


<br>

**Computer Modern and Computer Modern Mono:**

![image](https://github.com/cplusplus/nbballot/assets/6378233/278afee1-76fa-44c7-a524-b5b84ba75ce5)

**Comment by tkoeppe** [comment]
![image](https://github.com/cplusplus/nbballot/assets/6378233/d901c3c0-f4ff-4c57-a610-1a0fddef8899)

**Comment by tkoeppe** [comment]
Other families that seem to work quite well: Noto and Source.

![altfonts](https://github.com/cplusplus/nbballot/assets/6378233/afc76563-6d21-4baa-a332-7781e8c54198)
