### ISSUE TITLE
**-035 Incorrect reference format

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#577]
When a standard is cited, its document number is used. Please remove the title of ISO/IEC 9899:2018 in paragraph 2 of the Scope (and elsewhere in the document if it applies). Additionally, this paragraph states that that document will be referred to as the “C standard”. This is not in line with our format, please replace all instances of C standard by ISO/IEC 9899.

**Comment by jensmaurer** [comment]
Removing the title is easy; updating all mentions of "C standard" is likely a search&replace exercise that is not really helping anybody. But so be it.

**Comment by zygoloid** [comment]
Can we address this by distinguishing between the ISO document and the language defined by it?

**Comment by tkoeppe** [comment]
1) remove "C Standard" (cite properly)
2) define "C Standard Library" in Clause 3
