### ISSUE TITLE
**-036 Punctuation changes

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#578]
Replace behavior by behaviour
Replace e.g., by e.g.
Replace NOTE 1: by NOTE 1 (no colon)
Replace EXAMPLE 1: by EXAMPLE 1 (no colon)
Replace Table 1: by Table 1 — (colon is replaced by an em dash)

**Comment by jensmaurer** [comment]
Why British spelling in exactly one place?

"e.g." comma should be double-checked with a dictionary (or the Directives, if they say something here); there is good rationale that "e.g." is a sentence (albeit in Latin) and thus should use a comma afterwards.

**Comment by tkoeppe** [comment]
NOTE and EXAMPLE should already be correct.

**Comment by tkoeppe** [comment]
Tables (and figures) are fixable. I'm not sure what to do about the spelling; I thought American English was OK?

**Comment by tkoeppe** [comment]
The house style talks about "e.g." etc.: https://www.iso.org/ISO-house-style.html#iso-hs-s-text-r-a-eg

**Comment by JohelEGP** [comment]
> Why British spelling in exactly one place?

The house style also says "ISO documents use Oxford English spelling, which is British spelling [...]" (<https://www.iso.org/ISO-house-style.html#iso-hs-s-text-r-spelling>).
And searching for "behavior" in the linked online dictionary returns an entry for "behaviour" (<https://www.oxfordlearnersdictionaries.com/us/definition/english/behaviour?q=behavior>).

**Comment by jensmaurer** [comment]
Yes, ISO wants us to use British spelling throughout (except use -ize instead of -ise), but we've always pushed back on that on the grounds that the programming language we describe uses American spelling for their contents, and it would be odd to describe an American-spelled facility using British spelling next to it.

I though there was a rather punchy example in the standard library, but I can't find it right now. @zygoloid , do you remember?

**Comment by jensmaurer** [comment]
The part about commas after "e.g." and "i.e." seems to be a difference between American and British English (the former preferring the comma, the latter not so much):

https://www.quickanddirtytips.com/articles/i-e-versus-e-g/

>  I’ve also been told that the commas are used less frequently in Britain ...

**Comment by tkoeppe** [comment]
I'm happy to push back on this.

**Comment by tkoeppe** [comment]
For C++17 DIS we had responded:

> The document defines many terms that must be spelled the same way by conforming implementations and by users of those implementations, and these terms use US English spelling. It would be confusing for the document text to use UK English spelling when describing these terms.
