### ISSUE TITLE
**-037 Review "must"

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#579]
Review the use of “must” (used 74 times in the document). If the intention is to convey a requirement please use “shall”.
[ISO/IEC Directives Part 2, 7.6](https://www.iso.org/sites/directives/current/part2/index.xhtml#_idTextAnchor095):
Do not use “must” as an alternative for “shall”. This avoids confusion between the requirements of a document and external constraints (see 7.2).

**Comment by jensmaurer** [comment]
Uh, I thought we were careful to eradicate "must" the last time around. Maybe we overlooked that. Needs a bit of effort, in particular since phrasing in notes in difficult.

**Comment by jensmaurer** [comment]
@tkoeppe , @zygoloid , any idea what to do here?

**Comment by jensmaurer** [comment]
Instead of (e.g.) "must ... (xref)", we could say "Subclause xref requires that ..." This narrowly misses "is required to". Would that help?

**Comment by tkoeppe** [comment]
Last time: "we reviewed all the musts and none of them are establishing requirements"

**Comment by tkoeppe** [comment]
I asked ISO about this, and their response is:

> This use of must and cannot will likely create some confusion in the users. We would recommend that the notes which explain the requirements be made normal text, because "the document shall be usable without the notes." (DP2, 24.1). This would remove any constraints of language.  

I'd say this gives us enough reason to reject the associated comments and say that "[w]e reviewed all the uses, and their use in explanatory notes is as intended. The document is usable without the notes, and the notes, while helpful, would not make for good non-note text.

Alternatively, we could consider their proposal to move the notes to not be notes on a case-by-case basis?

**Comment by jensmaurer** [comment]
Surely there must be a way to explain non-normatively around some rule in section X that some other section Y has introduced a requirement, and thus section X doesn't have to deal with certain cases?

We absolutely need this facility in the C++ standard, and even if we might be able to convert some of our notes into normative text, the contents of those notes is absolutely not normative, and is not intended to be normative. For example, we skip some fine print that is given in the normative rule, or use vague language such as "some" if we don't want to repeat a normative rule in its entirety, risking confusion if the two end up deviating.

**Comment by jensmaurer** [comment]
Ah, right. Oh well, then.
