### ISSUE TITLE
**-038 No italics except cross-referenced terms in clause 3

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#580]
Only the terms defined in this document can be italicized in Clause 3 for cross-reference purposes and but not other content throughout the rest of the text. Please correct.

**Comment by jensmaurer** [comment]
This refers to our terms-defined-in-the-middle italics and our grammar non-terminals. I guess we should reject, but that probably doesn't satisfy ISO/CS.

**Comment by tkoeppe** [comment]
Hm, are we understanding this right? I think they are quoting a rule from the House Style, https://www.iso.org/ISO-house-style.html#iso-hs-s-text-r-r-ref_clause3. But that rule is about Clause 3 _itself_, and that _in Clause 3_ you should not use italics.

Maybe they're referring to our grammar terms?

**Comment by jensmaurer** [comment]
They definitely refer to our grammar terms, but also to our use of italics to define local terms throughout the standard. Note the phrasing "but not other content throughout the **rest of the text**." (emphasis mine)

**Comment by tkoeppe** [comment]
On which rule is this "rest of the text" based?

**Comment by jensmaurer** [comment]
ISO Directives, Part 2, 27.5 talks about multi-letter italics in math formulae.

More clear is the House Style: https://www.iso.org/ISO-house-style.html#iso-hs-s-formatting-r-d-italics

**Comment by tkoeppe** [comment]
I will try to reject this by explaining the grammar terms and see where that gets us.

**Comment by tkoeppe** [comment]
We will review Clause 3.
