### ISSUE TITLE
**-039 Notes

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#581]
ISO/IEC Directives Part 2, 24.5: ‘Notes shall not contain requirements (e.g. use of “shall”, see Table 3) or any information considered indispensable for the use of the document, for example instructions (imperative mood), recommendations (e.g. use of “should”, see Table 4) or permission (e.g. use of “may”, see Table 5).’
We suggest changing this to normal text instead.

See:

note in 5.6,
note 3 in 6.3,
note 3 in 6.4.2 (negative requirement),
note 1 in 6.4.4 (negative requirement),
note in 6.7.5.5.3 (negative requirement),
notes 2 and 3 in 6.8.1 (negative requirement), etc.

**Comment by jwakely** [comment]
None of these notes imposes any requirement that isn't already normatively stated. They are clarifying notes.

**Comment by jensmaurer** [comment]
Maybe "cannot" ends up as a trigger word these days; maybe we can rephrase as "is not" or "is never".

**Comment by jensmaurer** [comment]
Accepted with modifications.

Note 5.6 has "is required", which is equivalent to "shall".
Note 3 in 6.3 has "definition is required" in a comment in the nested example

Those two are fixed.

Note 3 in 6.4.2 has "cannot". According to the ISO Directives, Part 2, section 7.5, "cannot" expresses a (negative) technical capability, which seems adequate phrasing for a note.
Note 1 in 6.4.4 has "cannot". Same.
Note in 6.7.5.5.3 has "cannot". Same.
Notes 2 and 3 in 6.8.1 have "cannot". Same.

Those are unchanged.

**Comment by jensmaurer** [comment]
Maybe we merged this prematurely.

The House Style https://www.iso.org/ISO-house-style.html#iso-hs-s-text-r-s-need
says "Revise a sentence that uses “need(s) to” to avoid confusion and misapplication of the text."

If ISO/CS is unhappy with these changes (because they introduce "need to"), we should ask them how we should refer to requirements specified elsewhere in the document when writing a note. We don't have a good idea for that right now.

This would also inform our approach for "must". Almost all appearances are in notes where we cite requirements specified elsewhere.

**Comment by tkoeppe** [comment]
OK, no problem, I'll remove those commits, and we'll ask ISO as you suggest!

**Comment by tkoeppe** [comment]
To ask ISO "how are we to refer to normative (possibly negative) requirements established elsewhere in the document [in notes]", to highlight consquences etc. Why can we not use "must" and "cannot"?

**Comment by tkoeppe** [comment]
"cannot" seems to be expressly allowed to be used the way we use it.
