### ISSUE TITLE
**-040 6.8.2 [basic.fundamental] All notes labeled as "NOTE1"

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/nbballot#582]
In 6.8.2 all notes are labelled erroneously as NOTE1. Please correct.

**Comment by tkoeppe** [comment]
This is on me.

**Comment by jensmaurer** [comment]
This isn't visible on my locally-generated PDF. Did something go wrong in the DIS submission?

**Comment by tkoeppe** [comment]
Yes, I changed the formatting and numbering to the ISO format "NOTE", "NOTE 1", "NOTE 2", etc. The numbering requires some trickery because "notes shall be numbered only if there is more than one" :-S This must have gone wrong somehow.

**Comment by jensmaurer** [comment]
Ok, can we merge this to the main branch, too?

**Comment by tkoeppe** [comment]
I'd rather not. The ISO format is strictly inferior since it loses the _end_ marker.

I found the problem. It's rather silly. It's a 1 10 2 3 4 kind of situation.

**Comment by jensmaurer** [comment]
@tkoeppe, I think this is now fixed, right?

**Comment by tkoeppe** [comment]
Yes, thanks!
